### PR TITLE
Feature/2857 58 import syntax rebase

### LINKED ISSUE #85: Switch to more size-efficient import syntax
#### Describe the bug
When using our library in a project, all of the Material-UI components are included in the bundle even if they are never used.

#### What is the expected behavior?
Only the components that are being used should be part of the final bundle

#### What are the steps to reproduce?
1. Create a new authentication project with the CLI
2. Run the build command
3. Use a bundle analyzer to see that _all_ of the Material-UI components code is included in the final bundle, even the more obscure ones.

#### Screenshots or links to minimum reproduction example
image
		
#### Anything else to add?
This is reported by the Green team. This is something we need to be especially careful about, because a single instance of importing from the root will cause every component to be part of the bundle.

We need to update our component import syntax to use default exports instead of named exports from the index/barrel (i.e., we should not import anything from '@material-ui/core' in our library:

https://material-ui.com/guides/minimizing-bundle-size/#option-1

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #85 

#### Changes proposed in this Pull Request:
- Changed import statements of material-ui components to default imports
- Comp props and other things than components still be imported as named imports

### Screenshots:
**Before**
Screenshot 2022-01-21 at 4 40 29 PM

**After**
Screenshot 2022-01-21 at 4 54 13 PM

#### To Test:
1. Start a new React project with the pxblue cli via command line prompt npx -p @brightlayer-ui/cli blui new
2. Run yarn build from the login-workflow of the react-workflows in the updated branch you have locally.
3. The previous command should create a dist folder... copy the contents of that dist folder into your new cli generated projects node_modules/@brightlayer-ui/react-auth-workflow
4. Add the source-map-explorer to the cli generated project as a dev dependency and add "analyze" script "analyze": "source-map-explorer 'build/static/js/*.js'" 
5. Run yarn build in the new cli project
6. Run yarn analyze
7. Compare the new chart to the one posted in the PR

### CODE REVIEW

**Comment by emclaug2** [comment]
@bkarambe We should be all reset now; this branch matches the contents of your original feature branch.
For some reason I thought the Github revert would 'undo' the changes, but it just made another commit to manually undo everything.

**Comment by jeffvg** [comment]
The build size is smaller but like @emclaug2 mentioned in a prior pull request some of the pages are different. 

feature branch (missing mui divider)
image

local cli auth project (with mui divider)
image

**Comment by joebochill** [comment]
@bkarambe Are you looking into this?

**Comment by bkarambe** [comment]
> @bkarambe Are you looking into this?

Yes

**Comment by bkarambe** [comment]
> The build size is smaller but like @emclaug2 mentioned in a prior pull request some of the pages are different.
> 
> feature branch (missing mui divider) image
> 
> local cli auth project (with mui divider) image

Importing import { createStyles } from '@material-ui/core'; as default in styles/index.tsx is causing in all the Dialog. Reverted it.

**Comment by joebochill** [comment]
> Importing import { createStyles } from '@material-ui/core'; as default in styles/index.tsx is causing in all the Dialog. Reverted it.

isn't importing this from the barrel/index going to cause us to lose the bundle size improvements?

**Comment by emclaug2** [comment]
> > Importing import { createStyles } from '@material-ui/core'; as default in styles/index.tsx is causing in all the Dialog. Reverted it.
> 
> isn't importing this from the barrel/index going to cause us to lose the bundle size improvements?

I just tested this out locally and our bundle sizes have jumped from 1MB back up to 3MB, using the barrel file for this line will cost us the bundle size optimizations.

**Comment by emclaug2** [comment]
Looking a little more into this, the style differences are caused by the rules loading in a different order.  It seems the default material styles will have precedence.  I'm unsure how to alter the load order for the style rules, @joebochill have you seen this before?

CSS Before
CSS Before


CSS After
After CSS

**Comment by joebochill** [comment]
So there are multiple instances where createStyles (and some other style related functions) are defined. If you track down the one that is being exported from the barrel index file and import it from where it is originally defined, that _should_ work. 

But for informational purposes, you can read more about CSS injection order here: https://v4.mui.com/styles/advanced/#css-injection-order

**Comment by emclaug2** [comment]
@bkarambe are there any updates on this PR?  Does Joe's comment make sense?

**Comment by emclaug2** [comment]
@joebochill @bkarambe After merging in @joebochill 's PR the bundle size has been minimized and the screens look as expected.

**Comment by jeffvg** [comment]
looking at this now

**Comment by jeffvg** [comment]
looks good

image

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
