### PR TITLE
Revert "Feature/2857 85 more efficient import syntax"

### PR DESCRIPTION
**Pull request by emclaug2**
Reverts brightlayer-ui/react-workflows#99

Let's investigate why these style changes are happening before we keep the code changes.  

image
image
image

### CODE REVIEW

**Comment by emclaug2** [comment]
Whenever I approved the original feature branch, I didn't notice any style changes in the local example.   I must have been doing something incorrect last Friday because now I'm seeing these changes within the local demo.

**Comment by emclaug2** [comment]
@bkarambe @jeffvg  This is a reversion PR; it'll reset us back to dev before Suraj's last PR was made.

**Comment by jeffvg** [comment]
> @bkarambe @jeffvg This is a reversion PR; it'll reset us back to dev before Suraj's last PR was made.

ok was wondering. In the pics above, what was circled? looking at this now

**Review by jeffvg — APPROVED** [review]

**Comment by emclaug2** [comment]
@bkarambe Your original branch should be in-tact.

**Pull request merged**
