### PR TITLE
Remove mui/styles dependencies

### PR DESCRIPTION
**Pull request by daileytj**
Fixes BLUI-3661 && #170.

#### Changes proposed in this Pull Request:
- Remove mui/styles dependencies

#### To Test:
- `cd login-workflow && yarn initialize`
- `cd shared-auth && git checkout bug/fix-missing-type-definition-for-react-native`
- `cd .. && yarn start:example`
- ensure the example project still functions as expected using the latest mui/brightlayer-ui dependencies

### CODE REVIEW

**Comment by jeffvg** [comment]
from a fresh clone seeing this...shared-auth on dev

image

image

**Comment by emclaug2** [comment]
@daileytj is there a way to get this demo to work now?  I'm seeing the same issue that Jeff mentioned earlier.

**Comment by daileytj** [comment]
@jeffvg @emclaug2 are you using the updated react-auth-shared branch? https://github.com/brightlayer-ui/react-auth-shared/pull/86

**Comment by daileytj** [comment]
@jeffvg @emclaug2 I've updated the test instructions

**Comment by emclaug2** [comment]
> @jeffvg @emclaug2 I've updated the test instructions

Even from a fresh clone using these updated instructions I'm getting these errors still; @jeffvg are you seeing this or something different when using the new instructions? 

```
Module not found: Error: Can't resolve '../assets/images/background.svg' in 'C:\Users\Evan\Documents\git\pxblue\react-workflows\login-workflow\example\node_modules\@brightlayer-ui\react-auth-workflow\dist\components'
ERROR in ./node_modules/@brightlayer-ui/react-auth-workflow/dist/components/BrandedCardContainer.js 38:39-81
Module not found: Error: Can't resolve '../assets/images/background.svg' in 'C:\Users\Evan\Documents\git\pxblue\react-workflows\login-workflow\example\node_modules\@brightlayer-ui\react-auth-workflow\dist\components'

ERROR in ./node_modules/@brightlayer-ui/react-auth-workflow/dist/index.js 38:0-22
Module not found: Error: Can't resolve './index.css' in 'C:\Users\Evan\Documents\git\pxblue\react-workflows\login-workflow\example\node_modules\@brightlayer-ui\react-auth-workflow\dist'

ERROR in ./node_modules/@brightlayer-ui/react-auth-workflow/dist/screens/Login.js 68:47-97
Module not found: Error: Can't resolve '../assets/images/eaton_stacked_logo.png' in 'C:\Users\Evan\Documents\git\pxblue\react-workflows\login-workflow\example\node_modules\@brightlayer-ui\react-auth-workflow\dist\screens'

ERROR in ./node_modules/@brightlayer-ui/react-auth-workflow/dist/screens/Login.js 69:52-107
Module not found: Error: Can't resolve '../assets/images/cybersecurity_certified.png' in 'C:\Users\Evan\Documents\git\pxblue\react-workflows\login-workflow\example\node_modules\@brightlayer-ui\react-auth-workflow\dist\screens'

webpack compiled with 4 errors
No issues found.```

**Comment by jeffvg** [comment]
> > @jeffvg @emclaug2 I've updated the test instructions
> 
> Even from a fresh clone using these updated instructions I'm getting these errors still; @jeffvg are you seeing this or something different when using the new instructions?
> 
> ```
> Module not found: Error: Can't resolve '../assets/images/background.svg' in 'C:\Users\Evan\Documents\git\pxblue\react-workflows\login-workflow\example\node_modules\@brightlayer-ui\react-auth-workflow\dist\components'
> ERROR in ./node_modules/@brightlayer-ui/react-auth-workflow/dist/components/BrandedCardContainer.js 38:39-81
> Module not found: Error: Can't resolve '../assets/images/background.svg' in 'C:\Users\Evan\Documents\git\pxblue\react-workflows\login-workflow\example\node_modules\@brightlayer-ui\react-auth-workflow\dist\components'
> 
> ERROR in ./node_modules/@brightlayer-ui/react-auth-workflow/dist/index.js 38:0-22
> Module not found: Error: Can't resolve './index.css' in 'C:\Users\Evan\Documents\git\pxblue\react-workflows\login-workflow\example\node_modules\@brightlayer-ui\react-auth-workflow\dist'
> 
> ERROR in ./node_modules/@brightlayer-ui/react-auth-workflow/dist/screens/Login.js 68:47-97
> Module not found: Error: Can't resolve '../assets/images/eaton_stacked_logo.png' in 'C:\Users\Evan\Documents\git\pxblue\react-workflows\login-workflow\example\node_modules\@brightlayer-ui\react-auth-workflow\dist\screens'
> 
> ERROR in ./node_modules/@brightlayer-ui/react-auth-workflow/dist/screens/Login.js 69:52-107
> Module not found: Error: Can't resolve '../assets/images/cybersecurity_certified.png' in 'C:\Users\Evan\Documents\git\pxblue\react-workflows\login-workflow\example\node_modules\@brightlayer-ui\react-auth-workflow\dist\screens'
> 
> webpack compiled with 4 errors
> No issues found.```
> ```

everything worked with no issues with latest

**Comment by jeffvg** [comment]
everything looks good, don't see any errors. Just need to update existing-project-integration.md and remove @mui/styles entries

**Review by jeffvg — APPROVED** [review]
looks good, just my last comment

**Comment by emclaug2** [comment]
With the new submodule pointer this is working for me now. 👍

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
