### PR TITLE
Add validation file

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Add `VALIDATION.md` file for login workflow

### CODE REVIEW

**Comment by emclaug2** [comment]
This is the same validation file as angular's with updated unit test count & an additional test for validating Portuguese translations.

**Comment by jeffvg** [comment]
I don't think we have any console logging in this repo like we do in NG

**Comment by emclaug2** [comment]
Good catch, I'll have to remove or rephrase those checks for this & maybe RN.  I'll doublecheck RN.

**Comment by emclaug2** [comment]
> Good catch, I'll have to remove or rephrase those checks for this & maybe RN.

Thinking about this some more, it might be a good idea to keep the tests consistent between the frameworks & add console statements to each API-call service instead.  I can't think of another way to rephrase the tests, we'd have to remove them otherwise.

**Comment by emclaug2** [comment]
I've rephrased the console.log tests, should be good now.

**Pull request merged**
