### PR TITLE
Publish v2.5.0

### PR DESCRIPTION
**Pull request by daileytj**
#### Changes proposed in this Pull Request:
- Publishes v2.5.0

### CODE REVIEW

**Review by jeffvg — APPROVED** [review]
all translations and overall app looks good

**Comment by huayunh** [comment]
`yarn start:example` still gives me this in Portuguese for `custom-forgot-password-route` (the `<b>` tag). Is this to be expected?

image

In CHinese, the organization name is missing between the quotation marks on line 2. In English it was OK.
image

**Comment by jeffvg** [comment]
open issue for <b> tag is in auth shared. https://github.com/brightlayer-ui/react-auth-shared/issues/59

**Comment by huayunh** [comment]
> open issue for tag is in auth shared

So is it not supposed to be addressed in this round of release?

**Comment by jeffvg** [comment]
> > open issue for tag is in auth shared
> 
> So is it not supposed to be addressed in this round of release?

auth shared has - 
image

**Comment by huayunh** [comment]
yeah, so are you supposed to fix that in auth shared first, and update the react-auth-shared package version in this repo before releasing react workflow v2.5.0?

**Comment by jeffvg** [comment]
> yeah, so are you supposed to fix that in auth shared first, and update the react-auth-shared package version in this repo before releasing react workflow v2.5.0?

@daileytj 
should we update auth-shared to fix the above tag mentioned?

**Comment by joebochill** [comment]
The auth-shared issue should be fixed, but if it's going to be part of a minor release, the auth-workflow will pick it up automatically without any changes in the auth-workflow package (because it uses the caret syntax for dependencies). ...assuming the these issues are exclusively isolated to the auth-shared package (how confident are we of that?)

**Comment by emclaug2** [comment]
> The auth-shared issue should be fixed, but if it's going to be part of a minor release, the auth-workflow will pick it up automatically without any changes in the auth-workflow package (because it uses the caret syntax for dependencies). ...assuming the these issues are exclusively isolated to the auth-shared package (how confident are we of that?)

This is correct; I'll make a small PR to fix the auth-shared.

**Review by emclaug2 — APPROVED** [review]

**Comment by emclaug2** [comment]
Here's the PR to fix the Portuguese translations bold-text on Forgot Password: https://github.com/brightlayer-ui/react-auth-shared

**Pull request merged**
