### PR TITLE
Added fix for password field duplicate icon on edge

### PR DESCRIPTION
**Pull request by bkarambe**
https://github.com/brightlayer-ui/react-workflows/issues/173

BLUI-3645

#### Changes proposed in this Pull Request:
- Added display to pseudo css for ms

#### Screenshots:
Screenshot 2022-11-11 at 5 35 02 PM

#### To Test:
- cd login-workflow
- yarn start:example

### CODE REVIEW

**Review by huayunh — COMMENTED** [review]
you only fixed this for the examples, but doesn't this need to go into the login workflow source code itself as well?

**Review by daileytj — APPROVED** [review]
I'm ok with this approach. I tried to do some other things to avoid the global stylesheet to no avail. Good stuff. I'm approving this now, but be sure to update the changelog and package version number.

**Comment by daileytj** [comment]
I would also recommend writing up the story a an official react issue just to have a reference point that isn't the angular bug.

**Review by huayunh — APPROVED** [review]
Looks good. See what Tom says above.

**Pull request merged**
